# Generated by Django 6.0.3 on 2026-04-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='gamma',
        ),
    ]
