# Generated by Django 6.0.3 on 2026-04-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_good_gamma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='good',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='good',
            name='event',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img',
        ),
        migrations.RemoveField(
            model_name='good',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='good',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='good',
            name='price',
        ),
        migrations.RemoveField(
            model_name='good',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='good',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='good',
            name='style',
        ),
        migrations.CreateModel(
            name='GoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField(verbose_name='Повний Опис')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('event', models.CharField(max_length=30, verbose_name='Подія')),
                ('style', models.CharField(max_length=30, verbose_name='Стиль')),
                ('main_image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стара ціна')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.good')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
