# Generated by Django 6.0.3 on 2026-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_good_colors_remove_good_descr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodvariant',
            options={'verbose_name': 'Варіація товару', 'verbose_name_plural': 'Варіації товарів'},
        ),
        migrations.AlterField(
            model_name='goodvariant',
            name='main_image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
