# Generated by Django 6.0.3 on 2026-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_goodvariant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodvariant',
            old_name='main_image',
            new_name='img',
        ),
    ]
