# Generated by Django 6.0.3 on 2026-04-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_main_image_goodvariant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodvariant',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Відсоток знижки'),
        ),
    ]
