# Generated by Django 6.0.3 on 2026-04-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_goodvariant_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodvariant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
