# Generated by Django 6.0.3 on 2026-06-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='good',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
