# Generated by Django 6.0.3 on 2026-06-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_orderitem_order_remove_orderitem_good_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Нове', 'Нове'), ('В обробці', 'В обробці'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='Нове', max_length=20)),
                ('fname', models.CharField(verbose_name="Ім'я покупця")),
                ('sname', models.CharField(verbose_name='Прізвище покупця')),
                ('phone', models.CharField(verbose_name='Номер телефону покупця')),
                ('address', models.TextField(verbose_name='Адреса доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Побажання до замовлення')),
                ('total', models.PositiveIntegerField(null=True, verbose_name='Сума замовлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='main.goodvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.order')),
            ],
            options={
                'verbose_name': 'Замовлений товар',
                'verbose_name_plural': 'Замовлені товари',
            },
        ),
    ]
