# Generated by Django 6.0.3 on 2026-06-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
