# Generated by Django 6.0.3 on 2026-06-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodvariant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2026-06-08 00:33:59.318433+00:00', verbose_name='Дата викладення товару на сайт'),
            preserve_default=False,
        ),
    ]
