# Generated by Django 6.0.3 on 2026-06-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Чи оплачене замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Очікує на оплату', 'Очікує на оплату'), ('В обробці', 'В обробці'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='Нове', max_length=20),
        ),
    ]
