# Generated by Django 6.0.3 on 2026-06-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_orderitem_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='main.goodvariant'),
        ),
    ]
