upstream django {
    # web - це назва нашого контейнера з коду нижче
    server web:8000;
}

server {
    listen 80;

    # Усі звичайні запити кидаємо на Django
    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Стилі та скрипти Nginx віддає сам
    location /static/ {
        alias /app/static/;
    }

    # Фотографії товарів Nginx теж віддає сам
    location /media/ {
        alias /app/media/;
    }
}